# Created by trellis-cli vcanary
# Documentation: https://docs.roots.io/trellis/master/wordpress-sites/

wordpress_sites:
  sk-sos.kik.cat:
    site_hosts:
      - canonical: sk-sos.kik.cat
        redirects: []
    local_path: ../site
    branch: main
    repo: git@github.com:seenyat/sk-sos.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
